<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('tasks', function (Blueprint $table): void {
            $table->id();
            $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete();
            $table->foreignId('board_id')->constrained('boards')->cascadeOnDelete();
            $table->foreignId('board_column_id')->constrained('board_columns')->restrictOnDelete();
            $table->foreignId('task_type_id')->constrained('task_types')->restrictOnDelete();

            // Numbered per-board, e.g. PRD-42. Generated by observer on create.
            $table->unsignedInteger('number');
            $table->string('reference', 24)->nullable();

            $table->string('title', 500);
            $table->longText('description')->nullable();

            // 'low' | 'medium' | 'high' | 'critical'
            $table->string('priority', 16)->default('medium');

            $table->foreignId('parent_task_id')->nullable()->constrained('tasks')->cascadeOnDelete();
            $table->foreignId('reporter_id')->nullable()->constrained('users')->nullOnDelete();
            // Cached for fast list rendering; full assignee set is in task_assignees.
            $table->foreignId('primary_assignee_id')->nullable()->constrained('users')->nullOnDelete();

            $table->timestamp('start_date')->nullable();
            $table->timestamp('due_date')->nullable();
            $table->decimal('estimate_hours', 8, 2)->nullable();
            $table->decimal('logged_hours', 8, 2)->default(0);
            $table->unsignedTinyInteger('progress')->default(0); // 0–100

            // Sortable within a column. Float lets us insert between two rows
            // without reshuffling. Reseed periodically if precision degrades.
            $table->double('position');

            $table->timestamp('completed_at')->nullable();
            $table->timestamp('archived_at')->nullable();
            $table->timestamps();
            $table->softDeletes();

            $table->unique(['board_id', 'number']);
            $table->index(['tenant_id', 'board_id', 'board_column_id', 'position']);
            $table->index(['tenant_id', 'primary_assignee_id']);
            $table->index(['tenant_id', 'due_date']);
            $table->index(['parent_task_id']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('tasks');
    }
};
