<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Firm-level invoices generated by the monthly cycle-close cron. One row per
 * firm per billing period (calendar month). Stores the breakdown snapshot
 * (base price + per-client lines) so historical invoices stay correct even
 * if the firm later changes tier or deactivates clients.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('firm_invoices', function (Blueprint $table): void {
            $table->id();
            $table->foreignId('firm_id')->constrained('firms')->cascadeOnDelete();

            $table->string('invoice_number')->unique();
            $table->date('period_start');
            $table->date('period_end');

            $table->string('plan_tier', 30)->nullable()->comment('snapshot of firm.subscription_tier at invoice time');
            $table->unsignedInteger('base_amount')->default(0)->comment('EGP, plan base price');
            $table->unsignedInteger('clients_amount')->default(0)->comment('EGP, sum of per-client tier prices');
            $table->unsignedInteger('total_amount')->default(0)->comment('EGP, base + clients');
            $table->jsonb('line_items')->default('[]')->comment('snapshot of per-client tier breakdown');

            $table->string('status', 20)->default('pending')->comment('pending | paid | overdue | cancelled');
            $table->string('payment_method', 30)->nullable()->comment('bank_transfer | paymob | …');
            $table->string('payment_reference')->nullable();
            $table->timestamp('paid_at')->nullable();
            $table->foreignId('paid_by_user_id')->nullable()->constrained('users')->nullOnDelete();

            $table->timestamps();
            $table->softDeletes();

            $table->index(['firm_id', 'status']);
            $table->index(['firm_id', 'period_start']);
            $table->unique(['firm_id', 'period_start']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('firm_invoices');
    }
};
